# Generated by Django 2.0.2 on 2018-02-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='발매일')),
                ('agency', models.CharField(max_length=50)),
                ('production_company', models.CharField(max_length=50)),
            ],
        ),
    ]
