# Generated by Django 2.0.2 on 2018-02-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_remove_song_album'),
        ('album', '0002_auto_20180207_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
