# Generated by Django 2.0.2 on 2018-02-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_auto_20180207_1104'),
        ('album', '0004_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='name',
        ),
        migrations.AddField(
            model_name='album',
            name='img_cover',
            field=models.ImageField(blank=True, upload_to='album', verbose_name='커버이미지'),
        ),
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.CharField(default=2, max_length=50, verbose_name='앨범명'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(to='artist.Artist', verbose_name='아티스트 목록'),
        ),
    ]
