# Generated by Django 2.0.2 on 2018-02-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20180207_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
    ]
