# Generated by Django 2.0.2 on 2018-02-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_remove_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
    ]
