# Generated by Django 2.0.2 on 2018-02-07 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_remove_song_album'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='발매일')),
                ('agency', models.CharField(max_length=50)),
                ('production_company', models.CharField(max_length=50)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.Song')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='song',
            field=models.ManyToManyField(through='artist.Album', to='song.Song'),
        ),
    ]
